"""
scraper_debug.py

Shared helper so every scraper can save a copy of a page it failed to
parse (or that returned zero events unexpectedly), for later inspection.
Saved snapshots land in calendars/debug/ and get copied into the
published GH Pages site (as debug/) alongside a debug.html index
generated by src/generate_debug_index.py — see update_ics.yml.

calendars/ (and therefore calendars/debug/) is wiped at the start of
every run by src/main.py, so snapshots never accumulate across runs —
each run's debug.html only ever shows failures from that run.
"""

import os
import re
from datetime import datetime, timezone

DEBUG_DIR = "calendars/debug"

def save_debug_page(scraper_name, label, content):
    """Save `content` (a page's raw HTML/text) for later inspection.
    Returns the path it was saved to, or None if `content` was empty."""
    if not content:
        return None

    os.makedirs(DEBUG_DIR, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    safe_label = re.sub(r"[^A-Za-z0-9_-]+", "_", label).strip("_") or "page"
    filename = f"{scraper_name}_{safe_label}_{timestamp}.html"
    path = os.path.join(DEBUG_DIR, filename)

    with open(path, "w", encoding="utf-8", errors="replace") as f:
        f.write(content)

    print(f"Saved failed/unexpected page for debugging: {path}")
    return path